repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args: ['--max-line-length=500', '--ignore=E203,E266,E501,W503', '--max-complexity=18
', '--select=B,C,E,F,W,T4,B9']
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v4.3.16'
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.16.3
    hooks:
    -   id: pyupgrade
        args: ['--py3-plus']
