jobs:
- job: unit_tests
  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: conda env create --quiet --file environment.yml
    displayName: Create Anaconda environment

  - script: |
      source activate adaptive-scheduler
      python -c "import adaptive_scheduler"
    displayName: 'Import adaptive-scheduler'

- job: linting_tests
  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: |
      pip install pre_commit
      pre-commit install
      pre-commit run --all-files
    displayName: 'Run pre-commit'

  - script: |
      python conda-environment.py
      if [[ `git status --porcelain --untracked-files=no` ]]; then exit 1; fi
    displayName: Check if environment.yml is in sync with requirements.txt
