name: adaptive-scheduler

channels:
- conda-forge

dependencies:
  - python
  - adaptive
  - dill
  - ipyparallel
  - mpi4py
  - parse
  - psutil
  - pyzmq
  - structlog
  - tinydb
  - toolz
  - tqdm
  - pip:
    - m2r
