name: adaptive-scheduler

channels:
- conda-forge

dependencies:
  - python
  - adaptive
  - dill
  - ipyparallel
  - m2r
  - mpich
  - mpi4py
  - pandas
  - psutil
  - pyzmq
  - structlog
  - tinydb
  - toolz
  - tqdm
