name: adaptive-scheduler

channels:
- conda-forge

dependencies:
  - python
  - adaptive
  - dill
  - ipyparallel
  - mpich
  - mpi4py
  - pandas
  - psutil
  - pyzmq
  - structlog
  - tinydb
  - toolz
  - tqdm
  - pip:
      - m2r @ git+https://github.com/crossnox/m2r@dev#egg=m2r  # https://github.com/sphinx-doc/sphinx/issues/7420#issuecomment-610958327
